server:
  port: 9000

spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3307/cardsDB
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"

  #Docker command for RabbitMQ -   docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
  #rabbitmq:
  #  host: "localhost"
  #  port: 5672
  #  username: guest
  #  password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "cards"
    description: "Som Bank Cards Application"
    version: "1.0.0"