server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3308/loansDB
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"

  #Docker command for RabbitMQ -   docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
  #rabbitmq:
  #  host: "localhost"
  #  port: 5672
  #  username: guest
  #  password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "loans"
    description: "Som Bank Loans Application"
    version: "1.0.0"


logging:
  level:
    com:
      microservices:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"