server:
  port: 8090

spring:
  application:
    name: Loans
  datasource:
    url: jdbc:h2:mem:testdb2
    driverClassName: org.h2.Driver
    username: root2
    password: pass2
  h2:
    console:
      enabled: true
      path: /h2-db2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "qa"

build:
  version: "1.0"

loans:
  message: "Welcome to SomshubhraRoy Loans related local APIs "
  contactDetails:
    name: "Somshubhra Roy - Developer - LOCAL"
    email: "somshubhraroy98@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345