server:
  port: 8080

spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb1
    driverClassName: org.h2.Driver
    username: root1
    password: pass1
  h2:
    console:
      enabled: true
      path: /h2-db1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"