server:
  port: 8080

spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb1
    driverClassName: org.h2.Driver
    username: root1
    password: pass1
  h2:
    console:
      enabled: true
      path: /h2-db1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "1.0"

accounts:
  message: "Welcome to SomshubhraRoy Accounts related local APIs "
  contactDetails:
    name: "Somshubhra Roy - Developer - LOCAL"
    email: "somshubhraroy98@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
