spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:config/"
          #search-locations: "file:///D://microservices//config"
        git:
          uri: "https://github.com/som98/Microservices-Config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071
