server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms;cardNumber
    stream:
      bindings:
        #RabbitMQ bindings↓
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
          binder: rabbit
        emailsms-out-0:
          destination: communication-sent
          binder: rabbit
        #Kafka bindings↓
        cardNumber-in-0:
          destination: fetch-cardDetailsFromCards
          group: ${spring.application.name}
          binder: kafka
        cardNumber-out-0:
          destination: send-cardNumberToCards
          binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s