services:
  accountsDB:
    container_name: accountsDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsDB:
    container_name: cardsDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cardsDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansDB:
    container_name: loansDB
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loansDB
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "somshubhraroy/configserver:v3"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "somshubhraroy/accounts:v3"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      accountsDB:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsDB:3306/accountsDB"
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    image: "somshubhraroy/loans:v3"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      loansDB:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansDB:3306/loansDB"
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    image: "somshubhraroy/cards:v3"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      cardsDB:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsDB:3306/cardsDB"
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  somshubhra-roy:
    driver: "bridge"